### PR TITLE
Adding the lunr.js search feature

### PR DESCRIPTION
**Pull request by sylhare**
Allo,

As mentionned in #51  Add search support, here is my proposition with the lunr.js search feature.
I think it can be improved:

- [x] Make the search.css files into sass file ( in _sass/layout)
- [x] Consolidate the css of the input bar
- [x] Use the same format as the `<a>` for the search `<input>`

Here is how it looks anyway:
search

Now that there's a base I think we can improve on it. What do you think @rohanchandra ?
Thanks.

### CODE REVIEW

**Comment by rohanchandra** [comment]
This looks awesome @Sylhare! I'll have a look at the code a bit later.

I wonder if the search bar can somehow integrated into the header instead of a separate page:

bitmap

Perhaps the search bar can just attach a parameter to the `search.html` page request when the user clicks the search button (e.g. `search.html?query=search+text`), which is then parsed as the search query in your JavaScript used in `search.html`.

**Comment by sylhare** [comment]
Allo,

Well I think it's possible, it would require to put the input into the header and redirect it to a search result page as you mentionned (like the search page which would be hidden).
I can look to patch something like that.

**Comment by sylhare** [comment]
Ok so I tried it and it works. However I didn't change the css layout of the search bar in the header (it's raw for now). If you can help me a little I will be able to do it as you want 😉 

The search page is now on "hide" but when you click on search and validate you'll arrive to that page (with the same layout as above). If you see the link as the `search.html?query=sample` at the end. You can't see but I changed the placeholder in the header search bar for `Search...` as well.

Here is the screenshot:

search query

**Comment by rohanchandra** [comment]
Thanks @Sylhare for those changes for adding the search bar to the header. 👍 

I'll be able to work on getting the styling right a bit later, so I'll put this on hold for now.

**Comment by sylhare** [comment]
Ok good 😉, I might give it a try and publish some screenshot here. I will try to do the one you previously showed (with the search in grey and underlined).

**Comment by sylhare** [comment]
Hi @rohanchandra 

I have modified the layout to match your request:

search bar

Let me know if you like it. The `<form>` can be easily tweaked to match your padding/margin desire 😛

**Comment by rohanchandra** [comment]
Thanks @salmanulfarzy, that looks great. Can you make search a setting using `_config.yml`?

The easiest way would be to include a Boolean flag for search in `_config.yml`, like what we've done for `post_navigation`.

**Comment by sylhare** [comment]
Hi @rohanchandra 

I have put the option in the `_config.yml` under the katex one. Enabling it will make the search appear in the header. For the script it is in `search.html` and is only loaded when the page is loaded.
I put it to `false` as default so you keep the same layout.

**Comment by sylhare** [comment]
Hi @rohanchandra 

Are you satisfied with the feature? Is there anything you want me to do before adding it?
Let me know.

**Comment by rohanchandra** [comment]
Sorry for the delay @Sylhare.

Could you just add the license for the search code JS and a little bit of documentation for enabling the feature in the `README.md` file. 

For the JS, is there a way to directly integrate `Simple-Jekyll-Search` so there's less JS on our side (the docs for `Simple-Jekyll-Search` mention using `SimpleJekyllSearch` with a config)?

Thanks!

**Comment by sylhare** [comment]
Allo,

Well there's `simple-jekyll-search` and `lunr.js` for the jekyll search feature. Here we are using lunr.js, but I think we can have the `lunr.min.js` file online and imported in the `head.html` but the `search.js` local, or through a [gem jekyll plugin](https://github.com/slashdotdash/jekyll-lunr-js-search) but I don't think that gem will be accepted by github page

I can document that unless you want to go with `simple-jekyll-search `instead of `lunr.js`. I'll try some things in the meanwhile.

**Comment by rohanchandra** [comment]
Hey @Sylhare.

I think you're right in that custom gems can be used in GitHub Pages.

Let's keep it as is then.

**Comment by rohanchandra** [comment]
@Sylhare Got around to running a quick test for this feature.

1. Is it ok if we remove the search bar from the search results page:

image

There's already one at the top of the page, so we don't really need two.

2. On a local installation, clicking a link goes to the wrong page. The link goes to `http://127.0.0.1:4000/2014/11/30/sample-post.html` instead of `http://127.0.0.1:4000/type-theme/2014/11/30/sample-post.html`

3. The design for the search results page should match the tags page / index page. Here's the current design:

image

The main things to change are removing the underline from below each search result, and making sure the page headings are the same color as those on the index (see below).

image
 
4. Have you already tested gem compatibility?

5. Move `lunr.min.js` into a `vendor` folder within `js` or use a CDN link so we can separate the code not written specifically for the theme

6. `No results found` and the `Search` should be using a localization string instead of being hardcoded (localization strings are found in `_config.yml`)

**Comment by sylhare** [comment]
Allo,

I will be working on item 1, 2, 3 to make it work as you mentioned.
For 4, we could do something like a "search layout" as mentioned for tags in #59.
For 5, I can move it in a "vendor" folder, I have asked for a CDN link, but did only get one for a previous version, I'll see what I find.
For 6, I will see what I can do.

**Comment by rohanchandra** [comment]
@Sylhare For 5, here's a CDN link https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.1.4/lunr.min.js. Is this the version you need?

For 4, we should just be able to include it in the `spec.files` like you've done in #65 Updating gemspec without creating a separate layout right?

**Comment by sylhare** [comment]
Oh perfect! Thanks for the link, I'll make the tests, but it should be the same version.

For the 4, I'll update the gemfile then 😉 it should be ready soon.

**Comment by sylhare** [comment]
Allo,

I have worked and fixed everything (1, 2, 3, 5 - Used the CDN link, 6)
For 4 with the gemfile, I have combined it with the tags one here #66, I tested it and it was working.

Let me know if you're ok.

**Comment by rohanchandra** [comment]
Looks great, I'll have a play around with the design 👍

**Pull request merged**
